### ISSUE TITLE
Edit master document

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#92]
Edit our master document to add new requirements gathered at sponsor meeting 4/16

**Comment by Waschmid** [comment]
I've edited the master document in our test DB to accommodate the new requirements.

Categories now have many new fields, and they are as follows:

`max_signups (int)` : the maximum number of submissions a category can have in its submissions array
`min_servings (int)` : the minimum number of servings a submission to this category must have
`food (bool)` : is this category a food item or not? 
`min_vegan (int)` : the minimum number of submissions that must be vegan 

Note that for vegan submissions, the typical minimum servings number will not apply. For example, Jenn said that typically they have two main dishes that are 50+ servings, and then a 20 serving vegan option. I'm thinking we can add logic on the validation/submission end of things that if the vegan option is selected we use `min_servings / 3` to solve this. This is messy/hacky, but I'd like to avoid adding a whole other field just for `min_vegan_servings` or something. I'm very open to alternatives if anyone can think of any.

I added the `food` boolean so that we could potentially not render Veg/Vegan/GF checkboxes for these categories on the signup form, and also ignore logic regarding `min_vegan` submissions or other food-centric concerns.
