### ISSUE TITLE
Edit event template

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#94]
There is a lot of information that won't typically change from event to event (ie location, food categories, max serving amounts), so we have a master event from which newly created events load a lot of their data. However, it should be possible to change these basic details if necessary. Create an edit event form to change these.

**Comment by Waschmid** [comment]
Pic from 4/16 meeting:
![image](https://user-images.githubusercontent.com/26891896/56307438-b1587b80-60f9-11e9-82e7-b0891e6d0010.png)

The picture above is a little outdated already in that each category card will have to have fields for the new stuff in each category (see #92 for details). Namely, a `food` checkbox and `min_vegan`. If `food` is not checked, then the `min_vegan` input should be disabled.

Not pictured here (and also not really discussed at the meeting), but when the + button is clicked to add a new category, maybe a small modal should pop up to get the name? Since we have it as uneditable in the current mockup. Honestly up to whoever ends up building this component out, I'll leave it to their discretion.
